import { Category, Post, Severity, Status, User, Comment, LeaderboardUser, WardInfo } from "@/types";

/**
 * Mock dataset mirroring the backend seed (apps/api/prisma/seed.ts).
 * Used as a transparent fallback whenever NEXT_PUBLIC_API_URL is unset,
 * so the frontend is fully demoable without a running backend/DB.
 *
 * Coordinates are real Dhaka locations (lng, lat).
 */

export const MOCK_CURRENT_USER: User = {
  id: "user_demo_1",
  name: "Ayesha Rahman",
  email: "ayesha@example.com",
  ward: 33,
  role: "USER" as User["role"],
  isVolunteer: true,
  points: 245,
};

const dhakaAuthors = [
  { id: "u_rashed", name: "Rashed Khan" },
  { id: "u_nadia", name: "Nadia Islam" },
  { id: "u_tariq", name: "Tariq Aziz" },
  { id: "u_farhana", name: "Farhana Yasmin" },
  { id: "u_imran", name: "Imran Hossain" },
];

// Helper to make ISO timestamps offset from "now" so timeAgo() stays meaningful.
function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600 * 1000).toISOString();
}

export const MOCK_POSTS: Post[] = [
  {
    id: "post_1",
    title: "Severe waterlogging on Mirpur Road after last night's rain",
    body: "The road in front of Kazipara metro station is completely submerged. Rickshaws are overturning and commuters are stranded. This has been recurring every monsoon for 3 years. DSCC needs to clear the drains urgently.",
    category: Category.INFRASTRUCTURE,
    severity: Severity.EMERGENCY,
    status: Status.OPEN,
    lat: 23.8068,
    lng: 90.3686,
    address: "Mirpur Road, Kazipara",
    ward: 4,
    mediaUrls: [
      "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80"
    ],
    isAnon: false,
    aiAllowed: true,
    upvoteCount: 142,
    author: dhakaAuthors[0],
    hasVoted: false,
    commentCount: 18,
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
  {
    id: "post_2",
    title: "Broken streetlight junction — unsafe at night",
    body: "The streetlight at the Gulshan 2 circle junction has been out for two weeks. Pedestrians crossing at night are at risk, especially with the recent mugging reports nearby.",
    category: Category.SAFETY,
    severity: Severity.NORMAL,
    status: Status.IN_PROGRESS,
    lat: 23.7925,
    lng: 90.4078,
    address: "Gulshan Circle 2",
    ward: 18,
    mediaUrls: [
      "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80"
    ],
    isAnon: false,
    aiAllowed: true,
    upvoteCount: 67,
    author: dhakaAuthors[1],
    hasVoted: true,
    commentCount: 9,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(2),
  },
  {
    id: "post_3",
    title: "Potholes damaging vehicles on Banani 11 road",
    body: "Multiple deep potholes have formed between road 11 and road 79. Several bikes have skidded. Needs urgent filling before the rains worsen it.",
    category: Category.INFRASTRUCTURE,
    severity: Severity.NORMAL,
    status: Status.OPEN,
    lat: 23.7937,
    lng: 90.4066,
    address: "Banani Road 11",
    ward: 19,
    mediaUrls: [
      "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80"
    ],
    isAnon: false,
    aiAllowed: false,
    upvoteCount: 38,
    author: dhakaAuthors[2],
    hasVoted: false,
    commentCount: 4,
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
  },
  {
    id: "post_4",
    title: "Garbage piling up near Dhanmondi Lake — mosquito hazard",
    body: "Uncollected waste near the lake behind Rabindra Sarobar is rotting and breeding mosquitoes. Dengue risk is high this season. DSCC conservancy hasn't visited in over a week.",
    category: Category.ENVIRONMENT,
    severity: Severity.NORMAL,
    status: Status.OPEN,
    lat: 23.7466,
    lng: 90.376,
    address: "Dhanmondi Lake, Road 8A",
    ward: 47,
    mediaUrls: [
      "https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80"
    ],
    isAnon: false,
    aiAllowed: true,
    upvoteCount: 89,
    author: dhakaAuthors[3],
    hasVoted: false,
    commentCount: 12,
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(10),
  },
  {
    id: "post_5",
    title: "Snatching incident reported near Bashundhara gate",
    body: "Two youths on a motorcycle snatched a phone from a passerby near the main gate at 9pm. Sharing so neighbours stay alert. Please avoid walking alone here after dark.",
    category: Category.CRIME,
    severity: Severity.EMERGENCY,
    status: Status.OPEN,
    lat: 23.8133,
    lng: 90.4259,
    address: "Bashundhara Main Gate",
    ward: 7,
    mediaUrls: [],
    isAnon: true,
    aiAllowed: false,
    upvoteCount: 211,
    author: { id: "anon", name: "Anonymous" },
    hasVoted: false,
    commentCount: 31,
    createdAt: hoursAgo(14),
    updatedAt: hoursAgo(14),
  },
  {
    id: "post_6",
    title: "Traffic signal at Mohakhali not working",
    body: "The signal at Mohakhali intersection has been stuck/off for 3 days. Traffic police are manually managing it during peak hours but jams stretch to Kawran Bazar.",
    category: Category.TRAFFIC,
    severity: Severity.NORMAL,
    status: Status.RESOLVED,
    lat: 23.7785,
    lng: 90.4034,
    address: "Mohakhali Intersection",
    ward: 23,
    mediaUrls: [
      "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=800&q=80"
    ],
    isAnon: false,
    aiAllowed: false,
    upvoteCount: 54,
    author: dhakaAuthors[4],
    hasVoted: false,
    commentCount: 6,
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(6),
  },
  {
    id: "post_7",
    title: "Overflowing manhole near Baily Road market",
    body: "A manhole cover near the Baily Road kitchen market is overflowing with sewage. Foul smell and health hazard for shoppers and vendors. WASA needs to attend immediately.",
    category: Category.HEALTH,
    severity: Severity.NORMAL,
    status: Status.IN_PROGRESS,
    lat: 23.7366,
    lng: 90.4127,
    address: "Baily Road, Naya Paltan",
    ward: 33,
    mediaUrls: [],
    isAnon: false,
    aiAllowed: true,
    upvoteCount: 72,
    author: dhakaAuthors[0],
    hasVoted: true,
    commentCount: 11,
    createdAt: hoursAgo(20),
    updatedAt: hoursAgo(3),
  },
  {
    id: "post_8",
    title: "Illegal parking blocking Mirpur 10 ambulance access",
    body: "Cars parked illegally on both sides near Mirpur 10 roundabout are blocking the route to the local clinic. An ambulance was delayed 15 minutes yesterday.",
    category: Category.TRAFFIC,
    severity: Severity.NORMAL,
    status: Status.OPEN,
    lat: 23.8068,
    lng: 90.3686,
    address: "Mirpur 10 Roundabout",
    ward: 4,
    mediaUrls: [],
    isAnon: false,
    aiAllowed: false,
    upvoteCount: 45,
    author: dhakaAuthors[1],
    hasVoted: false,
    commentCount: 7,
    createdAt: hoursAgo(26),
    updatedAt: hoursAgo(26),
  },
  {
    id: "post_9",
    title: "Construction debris dumped on Mohammadpur footpath",
    body: "A large pile of bricks and concrete from nearby construction is blocking the entire footpath, forcing pedestrians onto the road. Reported multiple times, no action.",
    category: Category.ENVIRONMENT,
    severity: Severity.NORMAL,
    status: Status.RESOLVED,
    lat: 23.7706,
    lng: 90.3623,
    address: "Mohammadpur, Tajmahal Road",
    ward: 45,
    mediaUrls: [
      "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=800&q=80"
    ],
    isAnon: false,
    aiAllowed: false,
    upvoteCount: 33,
    author: dhakaAuthors[2],
    hasVoted: false,
    commentCount: 2,
    createdAt: hoursAgo(48),
    updatedAt: hoursAgo(20),
  },
  {
    id: "post_10",
    title: "Stray dog menace near Mirpur section 12 school",
    body: "A pack of aggressive stray dogs near the primary school has bitten two children this week. Parents are scared to send kids. Animal control / city corporation help needed.",
    category: Category.SAFETY,
    severity: Severity.NORMAL,
    status: Status.OPEN,
    lat: 23.8068,
    lng: 90.3589,
    address: "Mirpur Section 12",
    ward: 3,
    mediaUrls: [],
    isAnon: true,
    aiAllowed: true,
    upvoteCount: 96,
    author: { id: "anon", name: "Anonymous" },
    hasVoted: false,
    commentCount: 15,
    createdAt: hoursAgo(36),
    updatedAt: hoursAgo(36),
  },
];

export const MOCK_COMMENTS: Record<string, Comment[]> = {
  post_1: [
    {
      id: "c_1",
      body: "I was stranded near Kazipara station for 45 minutes this morning. DNCC Zone 4 emergency pumps must be activated immediately!",
      isAnon: false,
      postId: "post_1",
      author: { id: "u_nadia", name: "Nadia Islam", isVolunteer: true },
      createdAt: hoursAgo(0.8),
      replies: [
        {
          id: "c_1_1",
          body: "Spoke with Ward 4 Councillor office — they claimed a drainage clearance team is being dispatched by noon.",
          isAnon: false,
          postId: "post_1",
          parentId: "c_1",
          author: { id: "u_rashed", name: "Rashed Khan" },
          createdAt: hoursAgo(0.4),
        },
      ],
    },
    {
      id: "c_2",
      body: "Please avoid the leftmost lane when coming from Shewrapara; the ditch is completely invisible underwater.",
      isAnon: true,
      postId: "post_1",
      author: { id: "anon", name: "Anonymous" },
      createdAt: hoursAgo(0.5),
      replies: [],
    },
  ],
  post_2: [
    {
      id: "c_3",
      body: "Reported this to Gulshan Society Security wing as well. Hopefully they can expedite fixing the lamp post with DNCC.",
      isAnon: false,
      postId: "post_2",
      author: { id: "u_farhana", name: "Farhana Yasmin" },
      createdAt: hoursAgo(2),
      replies: [],
    },
  ],
  post_5: [
    {
      id: "c_4",
      body: "DMP Vatara Thana patrol has been alerted. Please stay in well-lit areas near Gate 1 and 2.",
      isAnon: false,
      postId: "post_5",
      author: { id: "u_imran", name: "Imran Hossain", isVolunteer: true },
      createdAt: hoursAgo(10),
      replies: [],
    },
  ],
};

export const MOCK_LEADERBOARD: LeaderboardUser[] = [
  {
    id: "user_demo_1",
    name: "Ayesha Rahman",
    ward: 33,
    points: 245,
    isVolunteer: true,
  },
  {
    id: "u_farhana",
    name: "Farhana Yasmin",
    ward: 47,
    points: 178,
    isVolunteer: true,
  },
  {
    id: "u_rashed",
    name: "Rashed Khan",
    ward: 4,
    points: 120,
    isVolunteer: false,
  },
  {
    id: "u_nadia",
    name: "Nadia Islam",
    ward: 18,
    points: 89,
    isVolunteer: true,
  },
  {
    id: "u_imran",
    name: "Imran Hossain",
    ward: 7,
    points: 74,
    isVolunteer: true,
  },
  {
    id: "u_tariq",
    name: "Tariq Aziz",
    ward: 19,
    points: 56,
    isVolunteer: false,
  },
];

export const MOCK_WARDS: WardInfo[] = [
  {
    wardNumber: 4,
    name: "Mirpur & Kazipara",
    areaNames: ["Mirpur Section 13", "Mirpur Section 14", "Kazipara", "Shewrapara"],
    totalPosts: 38,
    openIssues: 14,
    resolvedIssues: 24,
    councillorOffice: "Ward 4 Community Centre, Kazipara Main Road",
    emergencyPhone: "01711-234567",
  },
  {
    wardNumber: 18,
    name: "Gulshan-1 & 2",
    areaNames: ["Gulshan 1", "Gulshan 2", "Baridhara Diplomatic Zone"],
    totalPosts: 22,
    openIssues: 6,
    resolvedIssues: 16,
    councillorOffice: "Ward 18 Office, Gulshan Avenue",
    emergencyPhone: "01712-345678",
  },
  {
    wardNumber: 19,
    name: "Banani & Kakoli",
    areaNames: ["Banani Road 11", "Banani DOHS", "Kakoli"],
    totalPosts: 19,
    openIssues: 5,
    resolvedIssues: 14,
    councillorOffice: "Ward 19 Civic Center, Banani",
    emergencyPhone: "01713-456789",
  },
  {
    wardNumber: 33,
    name: "Baily Road & Naya Paltan",
    areaNames: ["Baily Road", "Siddheshwari", "Naya Paltan", "Kakrail"],
    totalPosts: 29,
    openIssues: 9,
    resolvedIssues: 20,
    councillorOffice: "Ward 33 Office, Baily Road",
    emergencyPhone: "01714-567890",
  },
  {
    wardNumber: 47,
    name: "Dhanmondi & Kalabagan",
    areaNames: ["Dhanmondi Lake", "Road 8A", "Road 27", "Kalabagan"],
    totalPosts: 41,
    openIssues: 11,
    resolvedIssues: 30,
    councillorOffice: "Ward 47 Centre, Dhanmondi 8/A",
    emergencyPhone: "01715-678901",
  },
  {
    wardNumber: 7,
    name: "Bashundhara & Kuril",
    areaNames: ["Bashundhara R/A", "Kuril", "Vatara"],
    totalPosts: 25,
    openIssues: 8,
    resolvedIssues: 17,
    councillorOffice: "Ward 7 Office, Kuril Chowrasta",
    emergencyPhone: "01716-789012",
  },
];

